---
Name: mailchimp-module
---
# MailChimp Module configuration
Member:
  extensions:
    - 'MCMemberExtension'
DataObject:
  extensions:
    - 'DataObjectExtension'
SiteConfig:
  extensions:
    - 'MCSiteConfigExtension'
  ## Set a different key for when the site is in dev mode
  DevAPIKey: '<Your dev API key>'
